### PR TITLE
Form vertical

### PR DESCRIPTION
**Pull request by quixote15**
I was thinking about best practices of UX/UI design for this Lib and based [on this article](https://medium.com/@allanroubertie/12-dicas-de-ux-para-criar-formulários-eficientes-6fc621a3ea05) and [Nilsen's heuristics](https://www.nngroup.com/articles/web-form-design/) I think it'd be great if we had a vertical version of the credit card form.

Since one of the recommendations of a better UI is to **Present fields in a single column layout.** 

> Multiple columns interrupt the vertical momentum of moving down the form. Rather than requiring users to visually reorient themselves, keep them in the flow by sticking to a single column with a separate row for each field.

So, here's what I did:

- Added a boolean `horizontal` flag to where True displays the form horizontally and False vertically
- Created a RN example project for this new feature (on the `exampleVertical/` folder)
- Added Android/IOS example Gifs to README.md
- Added the `horizontal` flag to the  REAMDE.me docs

The result is the following:

preview-vertical-android

### CODE REVIEW

**Comment by yuritoledo** [comment]
@quixote15 amazing man, thank you!

**Comment by yuritoledo** [comment]
@quixote15 I've downloaded here, and your example has 58mb. please remove all gif(and upload a link) and / or another files.

image

**Comment by quixote15** [comment]
> @quixote15 I've downloaded here, and your example has 58mb. please remove all gif(and upload a link) and / or another files.
> 
> image

I'm gonna create a repo to upload the example and gif files. I'll create another PR for that.

**Comment by yuritoledo** [comment]
Cool!

**Pull request merged**
